### ISSUE TITLE
Feature Request - Media Keys

### ISSUE THREAD

**Issue by gcormier** [malensek/3RVX#13]
In addition to volume, would it also be possible to add Play/Pause, Stop, Forward and Backward to the beta?

Codes

```
VK_MEDIA_NEXT_TRACK
0xB0

VK_MEDIA_PREV_TRACK
0xB1

VK_MEDIA_STOP
0xB2

VK_MEDIA_PLAY_PAUSE
0xB3
```

**Comment by malensek** [comment]
So pressing one of those media keys would display an OSD (like for play, pause, etc.)?

**Comment by gcormier** [comment]
Not quite... So you could map say ctrl-p to play/pause... For those of us
who don't have media keys on our keyboard :)

**Comment by malensek** [comment]
Ahhh, okay. Yeah, that would definitely be possible. I'll look into it.

**Comment by gcormier** [comment]
Just got the latest beta! Awesome!!!!

**Comment by malensek** [comment]
I guess that means it's working ;-). Are there any other keys that might be useful to emulate? I guess I could just add an option to supply custom VK codes as well.

**Comment by gcormier** [comment]
Yeah I think any VK codes would be the most versatile.. let people who have tenkeyless keyboards make up for their lack of keys ;)

**Comment by shrewdlogarithm** [comment]
Just a heads-up - media key mapping isn''t working for me (W7-64 - Beta6 or Beta7) - any ideas?

**Comment by malensek** [comment]
Is it mapping a media key (like say, the built-in volume up key) or the media key emulation that's not working? If it's media key emulation, what combination are you using? Thanks!

**Comment by shrewdlogarithm** [comment]
I'm trying to map Media->Play/Pause to a keyboard combo - I've tried a few different combos but none trigger Play/Pause (or Stop or Next/Prev) - I've had Spotify and WMP running and a proper media keyboard attached to check the media keys DO work - but none of my mappings trigger anything?

**Comment by malensek** [comment]
Reviewing what I did for this functionality, I think there's a few reasons this could be happening. I'm working on getting a much more robust handler for this done, and it'll also allow sending arbitrary keyboard keys as well. Hopefully I should have something ready to test soon... Thanks for your help :-)

**Comment by shrewdlogarithm** [comment]
Looking forward to it ;0

**Comment by shrewdlogarithm** [comment]
Cheekily posting as I noticed loads of committing and the start of Beta 9 release notes - are we close to another release? :)

**Comment by malensek** [comment]
It's here! :-)

Let me know if you're still having the same problem. If the media keys don't work, try creating a virtual key set to something like 41 (simulate pressing the letter 'A')

**Comment by shrewdlogarithm** [comment]
Good News - I can assign a media key now, YAY! - but there is an oddity

I'm using the zip (not the installed version) - if I run 3RVX and right-click the tray icon and select 'Settings' I can make changes - but 'Apply' or 'OK' will do one of the following
- crash 3VRX entirely
- cause it to become unresponsive - meaning the tray icon can be left-clicked for a volume slider but right-clicks do nothing and hotkeys aren't responsive

Killing it (if it's not crashed) and restarting it will pickup the changes in the settings and work OK tho - so that's a workaround.

Also - there does seem to be a 'focus' issue - sometimes the hotkeys won't trigger until you alt-tab out of what you're doing - I can't seem to pin-down an exact way of making that happen right now but I'll keep an eye and see if I can narrow it down (I suspect it might relate to interacting with the tray - I'm using W7-64 here) - alt-tabbing into another app usually 'wakes it up' tho

Thanks again for this - it really is just a smart way of controlling music - very handy!

**Comment by malensek** [comment]
Oh great, I can't believe I missed this. I will get a fix up asap, and then take a look at the focus issue. What kind of hotkey combination are you using that temporarily stops working? I ask because there are two different hotkey implementations working depending on the keys used.

**Comment by malensek** [comment]
Ok, I uploaded a version that fixes the crash. Thanks for catching that!

**Comment by shrewdlogarithm** [comment]
That fixes the crash - and I think the 'focus' thing might have been because I was using Alt-Middle-Mouse-Button for Play/Pause - if I use keyboard keys it seems more reliable?

I suspect having Alt-Wheel-Up and Alt-Wheel-Down for Volume means that they are called ahead of Alt-Middle-Mouse (because you will move the wheel a bit when you press it)??

I'll keep tinkering with that tho - and thanks again!
