### ISSUE TITLE
OSD not displaying on Windows 10 desktop... again

### ISSUE THREAD

**Issue by greatwroth** [malensek/3RVX#59]
This was resolved last time but it seems the issue has gotten worse. I am still running the latest 3RVX as admin on an up to date windows 10 setup but I've been slowly realizing (over the period of about a week XD) that the display will not show while the desktop is in focus. In addition if I send multiple requests (ex. rolling my G910 volume wheel back and forth) it's RAM and CPU usage will skyrocket (though still well within availability) and my cursor will start lagging. If I continue issuing requests the process will eventually become suspended and crash.

Also, just as a stress test, in normal working condition I was able to make 3RVX crash after a few seconds of issuing vol up/down and mute repeatedly, much faster than in the above issue but still manually issued on my G910... still well outside normal use.

**Comment by malensek** [comment]
From what I'm reading in Microsoft's docs, this changed with 8 and I may need to look into signing the executable rather than just having folks run it as administrator. The keyboard/mouse hooks also need to be moved to a separate thread to avoid getting de-registered, so that might contribute to this issue too.

Did 2.9.1 do the same thing? And what skin are you using? I can't replicate this on my machine but it might be a combination of settings/skin that I'm not hitting quite right.

**Comment by greatwroth** [comment]
Not sure about 2.9.1, don't think so but can try tomorrow. As for the skin, I'm actually using one I made myself, but I can provide the files if it will help.

**Comment by malensek** [comment]
Are you using the option to not show the OSD when a DirectX app is fullscreen by chance?

**Comment by greatwroth** [comment]
Yes I am.
