### ISSUE TITLE
Native Windows Volume OSD Still Shows

### ISSUE THREAD

**Issue by Valinwolf** [malensek/3RVX#99]
I was looking to replace the native OSD, however it does not go away. I'm running Win10 Pro 64 bit build 1909 with the version straight off the homepage, v2.9.2.

P.S.: Is this still being worked on? I noticed the last update to the code was a PR merge over 3 years ago.

**Comment by malensek** [comment]
It's been a long time since I've had enough free time to work on this, so unfortunately things have slowed down a lot... I'm open to spinning this off as an organization, adding maintainers, etc. if anybody is interested, though.

My Windows machine is dead, but at some point when I revive it I'm planning to at least go through the issues on Github to see if I can squash some lingering bugs.

**Comment by Valinwolf** [comment]
Yeah, I understand that. So I have a question... well, let me open another issue for that... I'm going to go ahead and close this, since it's no longer an issue.
